<?php
// Prefer the manually installed TCPDF in /tcpdf
$tcpdfPath = __DIR__ . '/../tcpdf/tcpdf.php';
$vendorTcpdfPath = __DIR__ . '/../vendor/tecnickcom/tcpdf/tcpdf.php';
$vendorAutoload = __DIR__ . '/../vendor/autoload.php';

if (file_exists($tcpdfPath)) {
    require_once $tcpdfPath;
} elseif (file_exists($vendorTcpdfPath)) {
    require_once $vendorTcpdfPath;
} elseif (file_exists($vendorAutoload)) {
    require_once $vendorAutoload;
} else {
    // TCPDF is not available; PDF generation will fail gracefully.
    // The Handover form will still submit, but no PDF will be attached.
}

class HandoverPDFGenerator {
    private $pdf;
    private $logoPath;
    
    public function __construct() {
        if (class_exists('TCPDF')) {
            $this->pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        } else {
            throw new Exception('TCPDF library not found. Please install via: composer require tecnickcom/tcpdf');
        }
        $this->logoPath = __DIR__ . '/../public/unikl-logo.png';
        $this->setupPDF();
    }
    
    private function setupPDF() {
        $this->pdf->SetCreator('UNIKL RCMP IT Inventory');
        $this->pdf->SetAuthor('UNIKL RCMP');
        $this->pdf->SetTitle('Asset Handover Document');
        $this->pdf->SetSubject('Equipment Handover Summary');
        $this->pdf->SetMargins(15, 20, 15);
        $this->pdf->SetAutoPageBreak(true, 20);
        $this->pdf->SetFont('helvetica', '', 10);
    }
    
    public function generate($data) {
        $this->addSummaryPage($data);
        $this->addPolicyPage($data);
        
        return $this->pdf->Output('', 'S');
    }
    
    private function addSummaryPage($data) {
        $this->pdf->AddPage();
        
        if (file_exists($this->logoPath)) {
            $this->pdf->Image($this->logoPath, 15, 13, 28, 0, '', '', '', false, 300, '', false, false, 0, false);
        }
        
        // Header
        $this->pdf->SetY(18);
        $this->pdf->SetFont('helvetica', 'B', 12);
        $this->pdf->Cell(0, 6, 'UNIVERSITY KUALA LUMPUR ROYAL COLLEGE OF MEDICINE PERAK', 0, 1, 'C');
        
        $this->pdf->Ln(4);
        $this->pdf->SetFont('helvetica', 'B', 14);
        $this->pdf->Cell(0, 8, 'ASSET HANDOVER SUMMARY', 0, 1, 'C');
        
        $this->pdf->Ln(6);
        $this->pdf->SetFont('helvetica', '', 9);
        $this->pdf->MultiCell(0, 5, 'This document is generated by the UNIKL RCMP IT Inventory System to record the details of an equipment handover.', 0, 'L');
        
        $this->pdf->Ln(8);
        
        // Helper for labeled rows
        $drawRow = function($label, $value) {
            $this->pdf->SetFont('helvetica', 'B', 9);
            $this->pdf->Cell(40, 6, $label, 0, 0, 'L');
            $this->pdf->SetFont('helvetica', '', 9);
            $this->pdf->Cell(0, 6, $value, 0, 1, 'L');
        };
        
        // Recipient section
        $this->pdf->SetFont('helvetica', 'B', 11);
        $this->pdf->Cell(0, 7, 'Recipient Information', 0, 1, 'L');
        $this->pdf->SetFont('helvetica', '', 9);
        
        $this->pdf->SetFillColor(245, 246, 250);
        $this->pdf->SetDrawColor(220, 221, 225);
        $this->pdf->SetLineWidth(0.2);
        $this->pdf->Cell(0, 30, '', 1, 1, 'L', true);
        
        $this->pdf->SetXY(16, $this->pdf->GetY() - 28);
        $drawRow('Staff Name', $data['staff_name'] ?? '');
        $drawRow('Staff ID', $data['staff_id'] ?? '');
        $drawRow('Faculty / Unit', $data['staff_designation'] ?? '');
        $drawRow('Email', $data['staff_email'] ?? '');
        
        $this->pdf->Ln(4);
        
        // Asset section
        $this->pdf->SetFont('helvetica', 'B', 11);
        $this->pdf->Cell(0, 7, 'Asset Details', 0, 1, 'L');
        $this->pdf->SetFont('helvetica', '', 9);
        
        $this->pdf->SetFillColor(245, 246, 250);
        $this->pdf->Cell(0, 32, '', 1, 1, 'L', true);
        
        $this->pdf->SetXY(16, $this->pdf->GetY() - 30);
        $drawRow('Asset ID', $data['asset_id'] ?? '');
        $drawRow('Category', $data['category'] ?? '');
        $drawRow('Brand / Model', trim(($data['brand'] ?? '') . ' ' . ($data['model'] ?? '')));
        $drawRow('Serial Number', $data['serial_num'] ?? '');
        $drawRow('Accessories', $data['accessories'] !== '' ? ($data['accessories'] ?? '') : 'N/A');
        
        $this->pdf->Ln(4);
        
        // Handover info
        $this->pdf->SetFont('helvetica', 'B', 11);
        $this->pdf->Cell(0, 7, 'Handover Details', 0, 1, 'L');
        $this->pdf->SetFont('helvetica', '', 9);
        
        $this->pdf->SetFillColor(245, 246, 250);
        $this->pdf->Cell(0, 22, '', 1, 1, 'L', true);
        
        $this->pdf->SetXY(16, $this->pdf->GetY() - 20);
        $drawRow('Handover Date', $data['handover_date'] ?? date('Y-m-d'));
        $drawRow('Location', $data['handover_location'] ?? '');
        $drawRow('Handled By', ($data['handover_by_name'] ?? 'IT Department') . ' (' . ($data['handover_by_designation'] ?? 'IT Staff') . ')');
        
        $this->pdf->Ln(6);
        
        if (!empty($data['handover_notes'])) {
            $this->pdf->SetFont('helvetica', 'B', 11);
            $this->pdf->Cell(0, 7, 'Additional Notes', 0, 1, 'L');
            $this->pdf->SetFont('helvetica', '', 9);
            $this->pdf->MultiCell(0, 5, $data['handover_notes'], 1, 'L');
            $this->pdf->Ln(4);
        }
        
        // System-generated disclaimer
        $this->pdf->Ln(4);
        $this->pdf->SetFont('helvetica', 'I', 8);
        $this->pdf->SetTextColor(100, 100, 100);
        $this->pdf->MultiCell(0, 4, 'This document is generated automatically from the UNIKL RCMP IT Inventory System. No physical signature is required.', 0, 'L');
        $this->pdf->SetTextColor(0, 0, 0);
    }
    
    private function addPolicyPage($data) {
        $this->pdf->AddPage();
        
        if (file_exists($this->logoPath)) {
            $this->pdf->Image($this->logoPath, 15, 13, 28, 0, '', '', '', false, 300, '', false, false, 0, false);
        }
        
        $this->pdf->SetY(18);
        $this->pdf->SetFont('helvetica', 'B', 12);
        $this->pdf->Cell(0, 6, 'UNIVERSITY KUALA LUMPUR ROYAL COLLEGE OF MEDICINE PERAK', 0, 1, 'C');
        
        $this->pdf->Ln(4);
        $this->pdf->SetFont('helvetica', 'B', 13);
        $this->pdf->Cell(0, 8, 'SOFTWARE & EQUIPMENT USAGE POLICY', 0, 1, 'C');
        
        $this->pdf->Ln(6);
        $this->pdf->SetFont('helvetica', '', 10);
        $this->pdf->MultiCell(0, 5, 'The following policy statements summarize the responsibilities of staff when using company-owned IT equipment and software.', 0, 'L');
        
        $this->pdf->Ln(4);
        
        $policies = [
            'UNIKL RCMP licenses the use of computer software from various vendors and does not own this software or its related documentation, unless explicitly stated. Unauthorized copying or reproduction is prohibited unless permitted by the license.',
            'Employees must use software only according to the relevant license agreements and must not install unauthorized copies of commercial software.',
            'Employees must not download or upload unauthorized software over the Internet.',
            'Any misuse of software or IT equipment that could be detrimental to the institution must be reported to the immediate supervisor.',
            'Under the Copyright Act 1987, offenders can be fined for each infringing copy and/or face imprisonment. UNIKL RCMP does not condone illegal duplication of software and may take disciplinary action, including termination.',
            'Any doubts about whether a particular software program may be copied or used should be raised with the immediate supervisor before proceeding.',
            'The assigned user is responsible for reasonable care of the issued equipment and may be held accountable for damage or loss due to negligence or intentional misconduct.'
        ];
        
        foreach ($policies as $index => $policy) {
            $this->pdf->Ln(2);
            $this->pdf->MultiCell(0, 5, ($index + 1) . '. ' . $policy, 0, 'L');
        }
        
        $this->pdf->Ln(8);
        $this->pdf->SetFont('helvetica', 'B', 10);
        $this->pdf->Cell(0, 6, 'Acknowledgement', 0, 1, 'L');
        
        $this->pdf->SetFont('helvetica', '', 9);
        $staffName = $data['staff_name'] ?? '[staff name]';
        $statement = "By accepting and using the assigned equipment, {$staffName} acknowledges that they have read and understood the above policy summary and agree to comply with it.";
        $this->pdf->MultiCell(0, 5, $statement, 0, 'L');
        
        $this->pdf->Ln(8);
        $this->pdf->SetFont('helvetica', 'I', 8);
        $this->pdf->SetTextColor(100, 100, 100);
        $this->pdf->MultiCell(0, 4, 'This acknowledgement is recorded electronically via the UNIKL RCMP IT Inventory Handover Form. No handwritten signature is required.', 0, 'L');
        $this->pdf->SetTextColor(0, 0, 0);
    }
}

function generateHandoverPDF($data) {
    try {
        $generator = new HandoverPDFGenerator();
        return $generator->generate($data);
    } catch (Exception $e) {
        error_log('PDF Generation Error: ' . $e->getMessage());
        return false;
    }
}
?>

