<?php
$oldErrorReporting = error_reporting();
$oldDisplayErrors = ini_get('display_errors');
$oldLogErrors = ini_get('log_errors');

error_reporting(0);
ini_set('display_errors', '0');
ini_set('log_errors', '0');

$tcpdfPath = __DIR__ . '/../tcpdf/tcpdf.php';
$vendorTcpdfPath = __DIR__ . '/../vendor/tecnickcom/tcpdf/tcpdf.php';
$vendorAutoload = __DIR__ . '/../vendor/autoload.php';

if (file_exists($tcpdfPath)) {
    @require_once $tcpdfPath;
} elseif (file_exists($vendorTcpdfPath)) {
    @require_once $vendorTcpdfPath;
} elseif (file_exists($vendorAutoload)) {
    @require_once $vendorAutoload;
} else {
    // TCPDF is not available; PDF generation will fail gracefully.
}

error_reporting($oldErrorReporting);
ini_set('display_errors', $oldDisplayErrors);
ini_set('log_errors', $oldLogErrors);

class ReturnPDFGenerator {
    private $pdf;
    private $logoPath;
    
    public function __construct() {
        if (class_exists('TCPDF')) {
            $oldErrorReporting = error_reporting();
            $oldDisplayErrors = ini_get('display_errors');
            $oldLogErrors = ini_get('log_errors');
            ini_set('display_errors', '0');
            ini_set('log_errors', '0');
            error_reporting(0);
            $this->pdf = @new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            error_reporting($oldErrorReporting);
            ini_set('display_errors', $oldDisplayErrors);
            ini_set('log_errors', $oldLogErrors);
        } else {
            throw new Exception('TCPDF library not found. Please install via: composer require tecnickcom/tcpdf');
        }
        $this->logoPath = __DIR__ . '/../public/unikl-rcmp.png';
        $this->setupPDF();
    }
    
    private function setupPDF() {
        $this->pdf->SetCreator('UNIKL RCMP IT Inventory');
        $this->pdf->SetAuthor('UNIKL RCMP');
        $this->pdf->SetTitle('Asset Return Document');
        $this->pdf->SetSubject('Equipment Return Summary');
        $this->pdf->SetMargins(15, 20, 15);
        $this->pdf->SetAutoPageBreak(false);
        $this->pdf->SetFont('helvetica', '', 10);
    }
    
    public function generate($data) {
        $this->addReturnPage($data);
        
        return $this->pdf->Output('', 'S');
    }
    
    private function addHeader($title = '') {
        $this->pdf->SetY(15);
        
        if (file_exists($this->logoPath)) {
            $logoWidth = 30;
            $x = 15;
            $this->pdf->Image($this->logoPath, $x, 15, $logoWidth, 0, '', '', '', false, 300, '', false, false, 0, false);
        }
        
        $this->pdf->SetY(18);
        $this->pdf->SetFont('helvetica', 'B', 11);
        $this->pdf->SetX(50);
        $this->pdf->Cell(0, 5, 'UNIVERSITY KUALA LUMPUR ROYAL COLLEGE OF MEDICINE PERAK', 0, 1, 'L');
        
        $this->pdf->SetX(50);
        $this->pdf->SetFont('helvetica', '', 9);
        $this->pdf->Cell(0, 5, 'INFORMATION TECHNOLOGY DEPARTMENT', 0, 1, 'L');
        
        if (!empty($title)) {
            $this->pdf->Ln(4);
            $this->pdf->SetFont('helvetica', 'B', 13);
            $this->pdf->Cell(0, 8, $title, 0, 1, 'C');
        }
    }
    
    private function addComputerGeneratedMessage() {
        $currentY = $this->pdf->GetY();
        $pageHeight = $this->pdf->GetPageHeight();
        $margin = 15;
        $footerHeight = 10;
        
        if ($currentY + $footerHeight > $pageHeight - $margin) {
            return;
        }
        
        $y = $pageHeight - $margin;
        $this->pdf->SetY($y);
        $this->pdf->Line(15, $y - 2, $this->pdf->GetPageWidth() - 15, $y - 2);
        $this->pdf->SetY($y);
        $this->pdf->SetFont('helvetica', 'I', 7);
        $this->pdf->SetTextColor(120, 120, 120);
        $this->pdf->Cell(0, 4, 'Generated by computer, don\'t need sign', 0, 1, 'C');
        $this->pdf->SetTextColor(0, 0, 0);
    }
    
    private function addReturnPage($data) {
        $this->pdf->AddPage();
        $this->addHeader('RETURN FORM OF COMPANY\'S DESKTOP');
        
        $this->pdf->Ln(8);
        
        // Staff Information Table
        $this->pdf->SetFont('helvetica', 'B', 10);
        $this->pdf->SetFillColor(240, 240, 240);
        $this->pdf->SetTextColor(0, 0, 0);
        
        $colWidths = [45, 40, 50, 0];
        $headers = ['Name', 'Staff ID', 'Designation', 'Department'];
        $values = [
            $data['staff_name'] ?? '',
            $data['staff_id'] ?? '',
            $data['staff_department'] ?? '',
            $data['staff_department'] ?? ''
        ];
        
        for ($i = 0; $i < count($headers); $i++) {
            $this->pdf->Cell($colWidths[$i], 8, $headers[$i], 1, 0, 'L', true);
        }
        $this->pdf->Ln();
        
        $this->pdf->SetFont('helvetica', '', 10);
        $this->pdf->SetFillColor(255, 255, 255);
        for ($i = 0; $i < count($values); $i++) {
            $this->pdf->Cell($colWidths[$i], 8, $values[$i], 1, 0, 'L', true);
        }
        $this->pdf->Ln(10);
        
        // Asset Information Section
        $this->pdf->SetFont('helvetica', 'B', 10);
        $this->pdf->Cell(0, 6, '1. Asset Information\'s', 0, 1, 'L');
        
        $this->pdf->Ln(2);
        $this->pdf->SetFont('helvetica', '', 10);
        
        $itemName = $data['category'] ?? 'Desktop';
        $assetInfo = [
            'i. Item Name:' => $itemName,
            'ii. Brand Name:' => $data['brand'] ?? '',
            'iii. Model Name:' => $data['model'] ?? '',
            'iv. Serial Number:' => $data['serial_num'] ?? '',
            'v. Asset ID:' => $data['asset_id'] ?? ''
        ];
        
        foreach ($assetInfo as $label => $value) {
            $this->pdf->Cell(50, 5, $label, 0, 0, 'L');
            $this->pdf->Cell(0, 5, $value, 0, 1, 'L');
        }
        
        $this->pdf->Ln(6);
        
        // Item Condition and Status Table
        $this->pdf->SetFont('helvetica', 'B', 10);
        $this->pdf->SetFillColor(240, 240, 240);
        
        $tableColWidths = [60, 70, 0];
        $tableHeaders = ['Item', 'Condition (OK/Damage)', 'Status (Return/Missing)'];
        
        for ($i = 0; $i < count($tableHeaders); $i++) {
            $this->pdf->Cell($tableColWidths[$i], 8, $tableHeaders[$i], 1, 0, 'C', true);
        }
        $this->pdf->Ln();
        
        $this->pdf->SetFont('helvetica', '', 10);
        $this->pdf->SetFillColor(255, 255, 255);
        
        // Desktop row
        $desktopCondition = $data['desktop_condition'] ?? 'OK';
        $desktopStatus = $data['desktop_status'] ?? 'RETURN';
        $this->pdf->Cell($tableColWidths[0], 8, 'Desktop', 1, 0, 'L', true);
        $this->pdf->Cell($tableColWidths[1], 8, $desktopCondition, 1, 0, 'C', true);
        $this->pdf->Cell($tableColWidths[2], 8, $desktopStatus, 1, 1, 'C', true);
        
        // Sub-items
        $subItems = [
            'Hard disk' => ['condition' => $data['harddisk_condition'] ?? 'OK', 'status' => $data['harddisk_status'] ?? 'RETURN'],
            'Monitor' => ['condition' => $data['monitor_condition'] ?? 'OK', 'status' => $data['monitor_status'] ?? 'RETURN'],
            'Mouse' => ['condition' => $data['mouse_condition'] ?? 'OK', 'status' => $data['mouse_status'] ?? 'RETURN'],
            'Keyboard' => ['condition' => $data['keyboard_condition'] ?? 'OK', 'status' => $data['keyboard_status'] ?? 'RETURN']
        ];
        
        foreach ($subItems as $item => $details) {
            $this->pdf->Cell(10, 7, '', 0, 0, 'L');
            $this->pdf->Cell($tableColWidths[0] - 10, 7, $item, 1, 0, 'L', true);
            $this->pdf->Cell($tableColWidths[1], 7, $details['condition'], 1, 0, 'C', true);
            $this->pdf->Cell($tableColWidths[2], 7, $details['status'], 1, 1, 'C', true);
        }
        
        // Remarks row
        $this->pdf->Cell($tableColWidths[0], 8, 'Remarks', 1, 0, 'L', true);
        $remarks = !empty($data['return_notes']) ? $data['return_notes'] : '';
        $this->pdf->SetFont('helvetica', '', 9);
        $this->pdf->Cell($tableColWidths[1] + $tableColWidths[2], 8, $remarks, 1, 1, 'L', true);
        
        $this->pdf->Ln(8);
        
        // Return Statement
        $this->pdf->SetFont('helvetica', '', 10);
        $staffName = $data['staff_name'] ?? '';
        $returnStatement = "I {$staffName}, return the hardware/peripherals as stated above in good/adverse conditions and checked perfectly by IT representative.";
        $this->pdf->MultiCell(0, 5, $returnStatement, 0, 'L');
        
        $this->pdf->Ln(10);
        
        // Handover by and Checked by sections (without signatures)
        $col1Width = 90;
        $col2Width = 90;
        $startX = $this->pdf->GetX();
        
        // Handover by section
        $this->pdf->SetFont('helvetica', 'B', 10);
        $this->pdf->Cell($col1Width, 6, 'Handover by:', 0, 0, 'L');
        
        // Checked by section
        $this->pdf->SetX($startX + $col1Width + 10);
        $this->pdf->Cell($col2Width, 6, 'Checked by:', 0, 1, 'L');
        
        $this->pdf->SetFont('helvetica', '', 10);
        
        // Handover by details
        $this->pdf->Cell(50, 6, 'Name:', 0, 0, 'L');
        $this->pdf->Cell($col1Width - 50, 6, $data['staff_name'] ?? '', 0, 0, 'L');
        
        // Checked by details
        $this->pdf->SetX($startX + $col1Width + 10);
        $this->pdf->Cell(50, 6, 'Name:', 0, 0, 'L');
        $this->pdf->Cell($col2Width - 50, 6, $data['received_by_name'] ?? 'IT Department', 0, 1, 'L');
        
        $this->pdf->Cell(50, 6, 'Designation:', 0, 0, 'L');
        $this->pdf->Cell($col1Width - 50, 6, $data['staff_department'] ?? '', 0, 0, 'L');
        
        $this->pdf->SetX($startX + $col1Width + 10);
        $this->pdf->Cell(50, 6, 'Designation:', 0, 0, 'L');
        $this->pdf->Cell($col2Width - 50, 6, $data['received_by_designation'] ?? 'IT TECHNICIAN', 0, 1, 'L');
        
        $this->pdf->Cell(50, 6, 'Date:', 0, 0, 'L');
        $this->pdf->Cell($col1Width - 50, 6, $data['return_date'] ?? date('d.m.Y'), 0, 0, 'L');
        
        $this->pdf->SetX($startX + $col1Width + 10);
        $this->pdf->Cell(50, 6, 'Date:', 0, 0, 'L');
        $this->pdf->Cell($col2Width - 50, 6, $data['return_date'] ?? date('d.m.Y'), 0, 1, 'L');
        
        $this->addComputerGeneratedMessage();
    }
    
}

function generateReturnPDF($data) {
    $oldErrorReporting = error_reporting();
    $oldDisplayErrors = ini_get('display_errors');
    $oldLogErrors = ini_get('log_errors');
    
    $oldErrorHandler = set_error_handler(function($errno, $errstr, $errfile, $errline) {
        if ($errno === E_DEPRECATED || $errno === E_STRICT || $errno === E_WARNING) {
            return true;
        }
        if (strpos($errfile, 'tcpdf') !== false) {
            return true;
        }
        return false;
    }, E_ALL);
    $obStarted = false;
    
    try {
        ini_set('display_errors', '0');
        ini_set('log_errors', '0');
        error_reporting(0);
        
        if (!ob_get_level()) {
            ob_start();
            $obStarted = true;
        }
        
        $generator = new ReturnPDFGenerator();
        $result = $generator->generate($data);
        
        if ($obStarted) {
            ob_end_clean();
        }
        
        error_reporting($oldErrorReporting);
        ini_set('display_errors', $oldDisplayErrors);
        ini_set('log_errors', $oldLogErrors);
        if ($oldErrorHandler !== null) {
            set_error_handler($oldErrorHandler);
        } else {
            restore_error_handler();
        }
        return $result;
    } catch (Exception $e) {
        if ($obStarted && ob_get_level()) {
            ob_end_clean();
        }
        error_reporting($oldErrorReporting);
        ini_set('display_errors', $oldDisplayErrors);
        ini_set('log_errors', $oldLogErrors);
        if ($oldErrorHandler !== null) {
            set_error_handler($oldErrorHandler);
        } else {
            restore_error_handler();
        }
        error_log('PDF Generation Error: ' . $e->getMessage());
        return false;
    }
}
?>

