-- UniKL RCMP IT Inventory System Database Schema
-- Database: inventory_system

CREATE DATABASE IF NOT EXISTS `inventory_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `inventory_system`;

-- Admin Table
CREATE TABLE IF NOT EXISTS `admin` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `staff_id` VARCHAR(100) NOT NULL UNIQUE,
    `name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_admin_staff_id` (`staff_id`),
    INDEX `idx_admin_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Technician Table
CREATE TABLE IF NOT EXISTS `technician` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `tech_id` VARCHAR(100) NOT NULL UNIQUE,
    `tech_name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('admin', 'technician') DEFAULT 'technician',
    `phone` VARCHAR(20) DEFAULT NULL,
    `profile_picture` VARCHAR(255) DEFAULT NULL,
    `status` ENUM('active', 'inactive') DEFAULT 'active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_tech_id` (`tech_id`),
    INDEX `idx_email` (`email`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Login Audit Trail Table
CREATE TABLE IF NOT EXISTS `login_audit` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `user_id` INT(11) DEFAULT NULL,
    `tech_id` VARCHAR(100) DEFAULT NULL,
    `email` VARCHAR(255) NOT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `user_agent` TEXT DEFAULT NULL,
    `login_status` ENUM('success', 'failed') NOT NULL,
    `failure_reason` VARCHAR(255) DEFAULT NULL,
    `login_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `logout_time` TIMESTAMP NULL DEFAULT NULL,
    `session_id` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_tech_id` (`tech_id`),
    INDEX `idx_email` (`email`),
    INDEX `idx_login_status` (`login_status`),
    INDEX `idx_login_time` (`login_time`),
    INDEX `idx_ip_address` (`ip_address`),
    FOREIGN KEY (`user_id`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Profile Audit Trail Table
CREATE TABLE IF NOT EXISTS `profile_audit` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `user_id` INT(11) DEFAULT NULL,
    `tech_id` VARCHAR(100) DEFAULT NULL,
    `email` VARCHAR(255) NOT NULL,
    `action_type` ENUM('update_profile', 'change_password', 'upload_picture', 'update_email', 'update_phone', 'update_name', 'admin_update') NOT NULL,
    `fields_changed` TEXT DEFAULT NULL,
    `old_values` TEXT DEFAULT NULL,
    `new_values` TEXT DEFAULT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `user_agent` TEXT DEFAULT NULL,
    `session_id` VARCHAR(255) DEFAULT NULL,
    `action_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_tech_id` (`tech_id`),
    INDEX `idx_email` (`email`),
    INDEX `idx_action_type` (`action_type`),
    INDEX `idx_action_time` (`action_time`),
    INDEX `idx_ip_address` (`ip_address`),
    FOREIGN KEY (`user_id`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Staff List Table
CREATE TABLE IF NOT EXISTS `staff_list` (
    `staff_id` INT(11) NOT NULL AUTO_INCREMENT,
    `staff_name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(255) DEFAULT NULL,
    `phone` VARCHAR(20) DEFAULT NULL,
    `faculty` VARCHAR(255) DEFAULT NULL,
    `status` ENUM('available', 'unavailable', 'queue', 'pending', 'handovers') DEFAULT 'available',
    `remarks` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT(11) DEFAULT NULL,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`staff_id`),
    INDEX `idx_staff_name` (`staff_name`),
    INDEX `idx_email` (`email`),
    INDEX `idx_status` (`status`),
    INDEX `idx_created_by` (`created_by`),
    INDEX `idx_updated_at` (`updated_at`),
    FOREIGN KEY (`created_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Network Assets Table
CREATE TABLE IF NOT EXISTS `net_assets` (
    `asset_id` INT(11) NOT NULL AUTO_INCREMENT,
    `serial` VARCHAR(100) DEFAULT NULL,
    `model` VARCHAR(100) DEFAULT NULL,
    `brand` VARCHAR(100) DEFAULT NULL,
    `mac_add` VARCHAR(17) DEFAULT NULL,
    `ip_add` VARCHAR(45) DEFAULT NULL,
    `building` VARCHAR(100) DEFAULT NULL,
    `level` VARCHAR(50) DEFAULT NULL,
    `status` VARCHAR(50) DEFAULT NULL,
    `PO_DATE` DATE DEFAULT NULL,
    `PO_NUM` VARCHAR(50) DEFAULT NULL,
    `DO_DATE` VARCHAR(50) DEFAULT NULL,
    `DO_NUM` VARCHAR(50) DEFAULT NULL,
    `INVOICE_DATE` DATE DEFAULT NULL,
    `INVOICE_NUM` VARCHAR(50) DEFAULT NULL,
    `PURCHASE_COST` DECIMAL(10,2) DEFAULT NULL,
    `warranty_expiry` DATE DEFAULT NULL,
    `remarks` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT(11) DEFAULT NULL,
    PRIMARY KEY (`asset_id`),
    INDEX `idx_serial` (`serial`),
    INDEX `idx_mac_add` (`mac_add`),
    INDEX `idx_ip_add` (`ip_add`),
    INDEX `idx_status` (`status`),
    INDEX `idx_warranty_expiry` (`warranty_expiry`),
    INDEX `idx_building_level` (`building`, `level`),
    FOREIGN KEY (`created_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audio Visual Assets Table
CREATE TABLE IF NOT EXISTS `av_assets` (
    `asset_id` INT(11) NOT NULL AUTO_INCREMENT,
    `class` VARCHAR(100) DEFAULT NULL,
    `brand` VARCHAR(100) DEFAULT NULL,
    `model` VARCHAR(100) DEFAULT NULL,
    `serial_num` VARCHAR(100) DEFAULT NULL,
    `location` VARCHAR(100) DEFAULT NULL,
    `status` VARCHAR(50) DEFAULT NULL,
    `PO_DATE` DATE DEFAULT NULL,
    `PO_NUM` VARCHAR(50) DEFAULT NULL,
    `DO_DATE` VARCHAR(50) DEFAULT NULL,
    `DO_NUM` VARCHAR(50) DEFAULT NULL,
    `INVOICE_DATE` DATE DEFAULT NULL,
    `INVOICE_NUM` VARCHAR(50) DEFAULT NULL,
    `PURCHASE_COST` DECIMAL(10,2) DEFAULT NULL,
    `remarks` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT(11) DEFAULT NULL,
    PRIMARY KEY (`asset_id`),
    INDEX `idx_class` (`class`),
    INDEX `idx_location` (`location`),
    INDEX `idx_status` (`status`),
    INDEX `idx_serial_num` (`serial_num`),
    FOREIGN KEY (`created_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Laptop/Desktop Assets Table
CREATE TABLE IF NOT EXISTS `laptop_desktop_assets` (
    `asset_id` INT(11) NOT NULL AUTO_INCREMENT,
    `serial_num` VARCHAR(100) DEFAULT NULL,
    `brand` VARCHAR(100) DEFAULT NULL,
    `model` VARCHAR(100) DEFAULT NULL,
    `acquisition_type` VARCHAR(100) DEFAULT NULL,
    `category` VARCHAR(100) DEFAULT NULL,
    `status` VARCHAR(50) DEFAULT NULL,
    `staff_id` INT(11) DEFAULT NULL,
    `assignment_type` VARCHAR(100) DEFAULT NULL,
    `location` VARCHAR(100) DEFAULT NULL,
    `processor` VARCHAR(100) DEFAULT NULL,
    `memory` VARCHAR(100) DEFAULT NULL,
    `os` VARCHAR(100) DEFAULT NULL,
    `storage` VARCHAR(100) DEFAULT NULL,
    `gpu` VARCHAR(100) DEFAULT NULL,
    `warranty_expiry` DATE DEFAULT NULL,
    `part_number` VARCHAR(100) DEFAULT NULL,
    `supplier` VARCHAR(100) DEFAULT NULL,
    `period` VARCHAR(100) DEFAULT NULL,
    `activity_log` TEXT DEFAULT NULL,
    `PO_DATE` DATE DEFAULT NULL,
    `PO_NUM` VARCHAR(50) DEFAULT NULL,
    `DO_DATE` DATE DEFAULT NULL,
    `DO_NUM` VARCHAR(50) DEFAULT NULL,
    `INVOICE_DATE` DATE DEFAULT NULL,
    `INVOICE_NUM` VARCHAR(50) DEFAULT NULL,
    `PURCHASE_COST` DECIMAL(10,2) DEFAULT NULL,
    `remarks` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`asset_id`),
    FOREIGN KEY (`staff_id`) REFERENCES `staff_list`(`staff_id`) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX `idx_serial_num` (`serial_num`),
    INDEX `idx_brand` (`brand`),
    INDEX `idx_model` (`model`),
    INDEX `idx_acquisition_type` (`acquisition_type`),
    INDEX `idx_category` (`category`),
    INDEX `idx_status` (`status`),
    INDEX `idx_staff_id` (`staff_id`),
    INDEX `idx_processor` (`processor`),
    INDEX `idx_memory` (`memory`),
    INDEX `idx_os` (`os`),
    INDEX `idx_storage` (`storage`),
    INDEX `idx_gpu` (`gpu`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Asset Trails Table
CREATE TABLE IF NOT EXISTS `asset_trails` (
    `trail_id` INT(11) NOT NULL AUTO_INCREMENT,
    `asset_type` ENUM('laptop_desktop', 'av', 'network') NOT NULL,
    `asset_id` INT(11) NOT NULL,
    `action_type` ENUM('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'ASSIGNMENT_CHANGE', 'LOCATION_CHANGE') NOT NULL,
    `changed_by` INT(11) DEFAULT NULL,
    `tech_id` VARCHAR(100) DEFAULT NULL,
    `field_name` VARCHAR(100) DEFAULT NULL,
    `old_value` TEXT DEFAULT NULL,
    `new_value` TEXT DEFAULT NULL,
    `description` TEXT DEFAULT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `user_agent` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`trail_id`),
    INDEX `idx_asset_type` (`asset_type`),
    INDEX `idx_asset_id` (`asset_id`),
    INDEX `idx_action_type` (`action_type`),
    INDEX `idx_changed_by` (`changed_by`),
    INDEX `idx_tech_id` (`tech_id`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_asset_composite` (`asset_type`, `asset_id`),
    FOREIGN KEY (`changed_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Handover Table
CREATE TABLE IF NOT EXISTS `handover` (
    `handover_id` INT(11) NOT NULL AUTO_INCREMENT,
    `staff_id` INT(11) NOT NULL,
    `asset_type` ENUM('laptop_desktop', 'av', 'network') NOT NULL,
    `asset_id` INT(11) NOT NULL,
    `handover_date` DATE NOT NULL,
    `handover_location` VARCHAR(255) DEFAULT NULL,
    `condition_agreement` BOOLEAN DEFAULT FALSE,
    `handover_notes` TEXT DEFAULT NULL,
    `digital_signoff` VARCHAR(100) DEFAULT NULL,
    `status` ENUM('active', 'returned', 'completed') DEFAULT 'active',
    `return_date` DATE DEFAULT NULL,
    `returned_by` INT(11) DEFAULT NULL,
    `return_condition` VARCHAR(50) DEFAULT NULL,
    `return_notes` TEXT DEFAULT NULL,
    `received_by_name` VARCHAR(100) DEFAULT NULL,
    `received_by_designation` VARCHAR(100) DEFAULT NULL,
    `desktop_condition` VARCHAR(20) DEFAULT NULL,
    `desktop_status` VARCHAR(20) DEFAULT NULL,
    `harddisk_condition` VARCHAR(20) DEFAULT NULL,
    `harddisk_status` VARCHAR(20) DEFAULT NULL,
    `monitor_condition` VARCHAR(20) DEFAULT NULL,
    `monitor_status` VARCHAR(20) DEFAULT NULL,
    `mouse_condition` VARCHAR(20) DEFAULT NULL,
    `mouse_status` VARCHAR(20) DEFAULT NULL,
    `keyboard_condition` VARCHAR(20) DEFAULT NULL,
    `keyboard_status` VARCHAR(20) DEFAULT NULL,
    `created_by` INT(11) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`handover_id`),
    INDEX `idx_staff_id` (`staff_id`),
    INDEX `idx_asset_type` (`asset_type`),
    INDEX `idx_asset_id` (`asset_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_handover_date` (`handover_date`),
    INDEX `idx_created_by` (`created_by`),
    INDEX `idx_returned_by` (`returned_by`),
    INDEX `idx_asset_composite` (`asset_type`, `asset_id`),
    FOREIGN KEY (`staff_id`) REFERENCES `staff_list`(`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`created_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`returned_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Repair / Faulty Intake Table
CREATE TABLE IF NOT EXISTS `repair_faulty` (
    `repair_id` INT(11) NOT NULL AUTO_INCREMENT,
    `asset_type` ENUM('laptop_desktop', 'av', 'network') NOT NULL,
    `asset_id` INT(11) NOT NULL,
    `reported_by` INT(11) DEFAULT NULL,
    `reported_by_name` VARCHAR(100) DEFAULT NULL,
    `severity` ENUM('Low', 'Medium', 'High', 'Critical') DEFAULT NULL,
    `issue_description` TEXT NOT NULL,
    `actions_performed` TEXT DEFAULT NULL,
    `parts_used` VARCHAR(255) DEFAULT NULL,
    `estimated_cost` DECIMAL(10,2) DEFAULT NULL,
    `vendor` VARCHAR(255) DEFAULT NULL,
    `return_actual_date` DATE DEFAULT NULL,
    `remarks` TEXT DEFAULT NULL,
    `created_by` INT(11) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`repair_id`),
    INDEX `idx_asset_type` (`asset_type`),
    INDEX `idx_asset_id` (`asset_id`),
    INDEX `idx_reported_by` (`reported_by`),
    INDEX `idx_severity` (`severity`),
    INDEX `idx_return_actual_date` (`return_actual_date`),
    INDEX `idx_created_by` (`created_by`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_asset_composite` (`asset_type`, `asset_id`),
    FOREIGN KEY (`reported_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`created_by`) REFERENCES `technician`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;